name: Build and Test React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Installer serve
        run: npm install -g serve

      - name: Build de l'application
        run: npm run build

      - name: Lancer l'application avec serve
        run: |
          serve -s build -l 3000 &
          sleep 5

      - name: Vérifier si l'application répond
        run: curl -f http://localhost:3000
